# Generated by Django 5.2.8 on 2025-11-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('LVE', 'On Leave'), ('DRP', 'Dropped Out')], default='ACT', max_length=3),
        ),
    ]
