# Generated by Django 5.2.8 on 2025-11-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_delays',
            field=models.PositiveIntegerField(default=0, help_text='Total number of late payments recorded.'),
        ),
        migrations.AddField(
            model_name='student',
            name='study_hours',
            field=models.PositiveIntegerField(default=0, help_text='Average self-reported study hours per week.'),
        ),
    ]
