# Generated by Django 5.2.8 on 2025-11-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_student_payment_delays_student_study_hours'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='grade',
            field=models.FloatField(default=0.0, help_text='Current grade in this specific course (0-100)'),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_grade',
            field=models.FloatField(default=0.0, help_text='Entrance Exam/Baseline Score (0-100)'),
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='schedule_snapshot',
        ),
    ]
