# Generated by Django 5.2.8 on 2025-11-22 03:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_enrollment_unique_together_enrollment_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='grade',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='current_average',
            field=models.FloatField(default=0.0, help_text='Calculated average (0-100)'),
        ),
        migrations.CreateModel(
            name='GradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='e.g. Quiz 1, Midterm, Homework', max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('score_obtained', models.FloatField(default=0.0, help_text='Points the student earned')),
                ('max_score', models.FloatField(default=100.0, help_text='Total points possible for this assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
